prefs_indexes = (  # by Koupah and Vresod,
	"lastPlayerName",
	"touchConfig",
	"colorConfig",
	"unused3",
	"unused4",
	"unused5",
	"unused6",
	"unused7",
	"ShowMinPlayerWarning",
	"showOnlineHelp",
	"lastHat",
	"sfxVolume",
	"musicVolume",
	"joyStickSize",
	"lastGameStart",
	"lastSkin",
	"lastPet",
	"censorChat",
	"lastLanguage",
	"vsync",
	"showAdsScreen2",
	"privacyPolicyVersion",
	"unused22",
	"birthDateMonth",
	"birthDateDay",
	"birthDateYear",
	"birthDateSetDate",
	"chatModeType",
	"isGuest",
	"guardianEmail",
	"hasLoggedin",
	"accountLoginStatus",
	"lastSchemaVersion",
	"lastVisor",
	"lastNameplate",
	"playerLevel",
	"playerXp",
	"lastCosmicube",
	"crossplayAllPlatforms",
	"playerXpRequiredForNextLevel",
	"enableMouseMovement",
	"askRedeemDLC",
	"warnedAboutGuestModeProgression",
)

hats = (  # by EnbyCosmog. special thanks to SharedLines for providing the initial version of this list
	"hat_NoHat",
	"hat_bushhat",
	"hat_captain",
	"hat_doubletophat",
	"hat_flowerpot",
	"hat_military",
	"hat_MilitaryWinter",
	"hat_GovtDesert",
	"hat_police",
	"hat_Rupert",
	"hat_partyhat",
	"hat_tophat",
	"hat_towelwizard",
	"hat_russian",
	"hat_viking",
	"hat_wallcap",
	"hat_pk06_Snowman",
	"hat_pk06_Reindeer",
	"hat_pk06_Lights",
	"hat_pk06_Santa",
	"hat_pk06_tree",
	"hat_pk06_Present",
	"hat_pk06_Candycanes",
	"hat_pk06_ElfHat",
	"hats_newyears2018",
	"hat_whitetophat",
	"hat_pk02_Crown",
	"hat_pk02_Eyebrows",
	"hat_pk02_HaloHat",
	"hat_pk02_PipCap",
	"hat_pk02_ScubaHat",
	"hat_pk02_StickminHat",
	"hat_pk02_StrawHat",
	"hat_pk02_ThirdEyeHat",
	"hat_pk02_ToiletPaperHat",
	"hat_pk02_Toppat",
	"hat_pk03_Fedora",
	"hat_pk03_StrapHat",
	"hat_pk04_Banana",
	"hat_pk04_Bear",
	"hat_pk05_Cheese",
	"hat_pk05_Cherry",
	"hat_pk05_Egg",
	"hat_pk05_Fedora",
	"hat_pk05_Flamingo",
	"hat_pk05_FlowerPin",
	"hat_pk05_Helmet",
	"hat_pk05_Plant",
	"hat_pkHW01_PlagueHat",
	"hat_pkHW01_CatEyes",
	"hat_pkHW01_Horns",
	"hat_pkHW01_BatWings",
	"hat_pkHW01_Mohawk",
	"hat_pkHW01_Pumpkin",
	"hat_pkHW01_ScaryBag",
	"hat_pkHW01_Witch",
	"hat_pkHW01_Wolf",
	"hat_pkHW01_Pirate",
	"hat_pkHW01_Machete",
	"hat_pk04_Archae",
	"hat_pk04_Balloon",
	"hat_pk04_BirdNest",
	"hat_pk04_Chef",
	"hat_pk04_CCC",
	"hat_pk04_Fez",
	"hat_pk04_GeneralHat",
	"hat_pk04_Pompadour",
	"hat_pk04_HunterCap",
	"hat_pk04_JungleHat",
	"hat_pk04_MiniCrewmate",
	"hat_pk04_Vagabond",
	"hat_pk04_Snowman",
	"hat_pk05_davehat",
	"hat_pk05_Ellie",
	"hat_pk05_Svenhat",
	"hat_pk05_Burthat",
	"hat_pk05_Ellryhat",
	"hat_pk05_Wizardhat",
	"hat_pk05_cheesetoppat",
	"hat_pk05_Macbethhat",
	"hat_pk05_HenryToppat",
	"hat_pk05_EllieToppat",
	"hat_pk05_GeoffreyToppat",
	"hat_Chocolate",
	"hat_Heart",
	"hat_Ponytail",
	"hat_Rubberglove",
	"hat_Unicorn",
	"hat_Zipper",
	"hat_CuppaJoe",
	"hat_HardtopHat",
	"hat_Prototype",
	"hat_Records",
	"hat_ThomasC",
	"hat_ToppatHair",
	"hat_WilfordIV",
	"hat_Winston",
	"hat_AbominalHat",
	"hat_EarmuffGreen",
	"hat_EarmuffsPink",
	"hat_EarmuffsYellow",
	"hat_EarnmuffBlue",
	"hat_pk04_MinerCap",
	"hat_MinerBlack",
	"hat_MinerYellow",
	"hat_RockIce",
	"hat_RockLava",
	"hat_SnowbeanieGreen",
	"hat_SnowbeanieOrange",
	"hat_SnowBeaniePurple",
	"hat_SnowbeanieRed",
	"hat_WinterHelmet",
	"hat_pk04_WinterHat",
	"hat_WinterGreen",
	"hat_WinterRed",
	"hat_WinterYellow",
	"hat_Voleyball",
	"hat_Basketball",
	"hat_Bowlingball",
	"hat_Deitied",
	"hat_Dodgeball",
	"hat_DrillMetal",
	"hat_DrillStone",
	"hat_DrillWood",
	"hat_Janitor",
	"hat_Pot",
	"hat_Soccer",
	"hat_Visor",
	"hat_mira_bush",
	"hat_mira_case",
	"hat_mira_cloud",
	"hat_mira_flower",
	"hat_mira_flower_red",
	"hat_mira_gem",
	"hat_pk03_Headphones",
	"hat_GovtHeadset",
	"hat_mira_headset_blue",
	"hat_mira_headset_pink",
	"hat_mira_headset_yellow",
	"hat_mira_leaf",
	"hat_mira_milk",
	"hat_pk04_Slippery",
	"hat_mira_sign_blue",
	"hat_pk03_Security1",
	"hat_pk04_Antenna",
	"hat_Antenna_Black",
	"hat_astronaut",
	"hat_Astronaut-Blue",
	"hat_Astronaut-Cyan",
	"hat_Astronaut-Orange",
	"hat_pk04_Bandana",
	"hat_Bandana_Blue",
	"hat_Bandana_Green",
	"hat_Bandana_Pink",
	"hat_Bandana_Red",
	"hat_Bandana_White",
	"hat_Bandana_Yellow",
	"hat_pk01_BaseballCap",
	"hat_baseball_Black",
	"hat_baseball_Green",
	"hat_baseball_Lightblue",
	"hat_baseball_LightGreen",
	"hat_baseball_Lilac",
	"hat_baseball_Orange",
	"hat_baseball_Pink",
	"hat_baseball_Purple",
	"hat_baseball_Red",
	"hat_baseball_White",
	"hat_baseball_Yellow",
	"hat_pk04_Beanie",
	"hat_Beanie_Black",
	"hat_Beanie_Blue",
	"hat_Beanie_Green",
	"hat_Beanie_Lightblue",
	"hat_Beanie_LightGreen",
	"hat_Beanie_LightPurple",
	"hat_Beanie_Pink",
	"hat_Beanie_Purple",
	"hat_Beanie_White",
	"hat_Beanie_Yellow",
	"hat_stethescope",
	"hat_Doc_black",
	"hat_Doc_Orange",
	"hat_Doc_Purple",
	"hat_Doc_Red",
	"hat_Doc_White",
	"hat_pk04_DoRag",
	"hat_Dorag_Black",
	"hat_Dorag_Desert",
	"hat_Dorag_Jungle",
	"hat_Dorag_Purple",
	"hat_Dorag_Sky",
	"hat_Dorag_Snow",
	"hat_Dorag_Yellow",
	"hat_pk03_Goggles",
	"hat_goggles",
	"hat_Goggles_Black",
	"hat_Goggles_Chrome",
	"hat_hardhat",
	"hat_Hardhat_black",
	"hat_Hardhat_Blue",
	"hat_Hardhat_Green",
	"hat_Hardhat_Orange",
	"hat_Hardhat_Pink",
	"hat_Hardhat_Purple",
	"hat_Hardhat_Red",
	"hat_Hardhat_White",
	"hat_brainslug",
	"hat_headslug_Purple",
	"hat_headslug_Red",
	"hat_headslug_Yellow",
	"hat_headslug_White",
	"hat_pk02_HeroCap",
	"hat_Herohood_Black",
	"hat_Herohood_Blue",
	"hat_Herohood_Pink",
	"hat_Herohood_Purple",
	"hat_Herohood_Red",
	"hat_Herohood_White",
	"hat_Herohood_Yellow",
	"hat_paperhat",
	"hat_Paperhat_Black",
	"hat_Paperhat_Blue",
	"hat_Paperhat_Cyan",
	"hat_Paperhat_Lightblue",
	"hat_Paperhat_Pink",
	"hat_Paperhat_Yellow",
	"hat_pk02_PlungerHat",
	"hat_Plunger_Blue",
	"hat_Plunger_Yellow",
	"hat_pk04_RamHorns",
	"hat_Ramhorn_Black",
	"hat_Ramhorn_Red",
	"hat_Ramhorn_White",
	"hat_pk02_TenGallonHat",
	"hat_TenGallon_Black",
	"hat_TenGallon_White",
	"hat_pk03_Traffic",
	"hat_Traffic_Blue",
	"hat_Traffic_Red",
	"hat_Traffic_Yellow",
	"hat_traffic_purple",
	"hat_devilhorns_yellow",
	"hat_arrowhead",
	"hat_axe",
	"hat_papermask",
	"hat_bat_crewcolor",
	"hat_bat_green",
	"hat_bat_ice",
	"hat_bone",
	"hat_candycorn",
	"hat_cat_grey",
	"hat_cat_orange",
	"hat_cat_pink",
	"hat_cat_snow",
	"hat_clown_purple",
	"hat_devilhorns_crewcolor",
	"hat_devilhorns_green",
	"hat_devilhorns_murky",
	"hat_devilhorns_white",
	"hat_devilhorns_black",
	"hat_fairywings",
	"hat_fishhed",
	"hat_frankenbolts",
	"hat_frankenbride",
	"hat_glowstick",
	"hat_mohawk_bubblegum",
	"hat_mohawk_bumblebee",
	"hat_mohawk_purple_green",
	"hat_mohawk_rainbow",
	"hat_mummy",
	"hat_tombstone",
	"hat_witch_green",
	"hat_witch_murky",
	"hat_witch_pink",
	"hat_witch_white",
	"hat_wolf_murky",
	"hat_wolf_grey",
	"hat_vi",
	"hat_caitlin",
	"hat_clagger",
	"hat_comper",
	"hat_enforcer",
	"hat_heim",
	"hat_jayce",
	"hat_jinx",
)

skins_dict = { # by EnbyCosmog. special thanks to SharedLines for providing the initial version of this list
	'skin_None': 'None', 
	'skin_Capt': "Pilot's License", 
	'skin_Police': 'Policeman Officer', 
	'skin_Wall': 'Guarding the Wall', 
	'skin_Security': 'Keepin it Secure', 
	'skin_Tarmac': 'Land Here', 
	'skin_Archae': 'Unearthed Wonders', 
	'skin_CCC': 'Chaos Containment Crewmate', 
	'skin_rhm': 'Right Hand Man: Reborn', 
	'skin_Bling': 'Bling Bling', 
	'skin_General': 'General Galeforce', 
	'skin_Mech': "I'll Fix it", 
	'skin_MechanicRed': 'Airship Mechanic', 
	'skin_Military': 'Officer Outfit', 
	'skin_MilitaryDesert': 'Officer - Desert', 
	'skin_MilitarySnowskin': 'Officer - Snow', 
	'skin_prisoner': 'Inmate 2112', 
	'skin_PrisonerBlue': 'Inmate 2112 - Blue', 
	'skin_PrisonerTanskin': 'Inmate 2112 - Tan', 
	'skin_SuitB': 'Suited up', 
	'skin_SuitW': 'Flashy', 
	'skin_Skin_SuitRedskin': 'Toppat Uniform', 
	'skin_ToppatSuitFem': 'Toppat Skirt', 
	'skin_ToppatVest': 'Vested Interest', 
	'skin_Winter': 'Jacket up', 
	'skin_JacketGreenskin': 'Jacket up - Green', 
	'skin_JacketPurpleskin': 'Jacket up - Purple', 
	'skin_JacketYellowskin': 'Jacket up - Yellow', 
	'skin_Abominalskin': 'Abominal Snowmate', 
	'skin_Miner': 'Underminer', 
	'skin_MinerBlackskin': 'Underminer - Black', 
	'skin_RockIceskin': 'Ice to Meet You', 
	'skin_RockLavaskin': 'Rock Solid', 
	'skin_Sweaterskin': 'Cozy Sweater', 
	'skin_SweaterBlueskin': 'Cozy Sweater - Blue', 
	'skin_SweaterPinkskin': 'Cozy Sweater - Pink', 
	'skin_SweaterYellowskin': 'Cozy Sweater - Yellow', 
	'skin_SportsRedskin': 'Sports Team Red', 
	'skin_SportsBlueskin': 'Sports Team Blue', 
	'skin_D2Cskin': 'Digging Kid', 
	'skin_Janitorskin': 'Janitorial Duties', 
	'skin_Bushskin': 'Sneaky', 
	'skin_BusinessFemskin': 'Business Skirt', 
	'skin_BusinessFem-Aquaskin': 'Business Skirt - Aqua', 
	'skin_BusinessFem-Tanskin': 'Business Skirt - Tan', 
	'skin_Hazmat': 'Hazmate', 
	'skin_Hazmat-Blackskin': 'Hazmate - Black',
	'skin_Hazmat-Blueskin': 'Hazmate - Blue',
	'skin_Hazmat-Greenskin': 'Hazmate - Green',
	'skin_Hazmat-Pinkskin': 'Hazmate - Pink',
	'skin_Hazmat-Redskin': 'Hazmate - Red',
	'skin_Hazmat-Whiteskin': 'Hazmate - White',
	'skin_Astro': 'Astronaught',
	'skin_Astronaut-Blueskin': 'Astronaut - Blueskin',
	'skin_Astronaut-Cyanskin': 'Astronaut - Cyanskin',
	'skin_Astronaut-Orangeskin': 'Astronaut - Orangeskin',
	'skin_Science': 'Scientific Theory',
	'skin_Scientist-Blueskin': 'Doctor',
	'skin_Scientist-Darkskin': 'Dark Scientist',
	'skin_clown': 'Crewbo the Clown',
	'skin_fairy': 'Fairy Godcrewmate',
	'skin_fishmonger': 'The Fishmonger',
	'skin_mummy': 'I Want my Mummy',
	'skin_pumpkin': "Big Ol' Pumpkin Pants",
	'skin_vampire': 'I Vant to Keel',
	'skin_witch': 'Whimsy Witch',
	'skin_caitlin': "Caitlyn's Uniform",
	'skin_enforcer': 'Enforcer Armor',
	'skin_heim': "Heimerdinger's Suit",
	'skin_jayce': "Jayce's Council Suit",
	'skin_jinx': "Jinx's Clothes",
	'skin_vi': "Vi's Clothes"
}

visors = (  # by EnbyCosmog. special thanks to Sharedlines for providing the initial version of this list
	"visor_EmptyVisor",
	"visor_pk01_FredVisor",
	"hat_geoff",
	"visor_pk01_MonoclesVisor",
	"visor_pk01_PaperMaskVisor",
	"visor_pk01_PlagueVisor",
	"visor_pk01_RHMVisor",
	"visor_pk01_Security1Visor",
	"visor_pk01_AngeryVisor",
	"visor_BillyG",
	"visor_Galeforce",
	"visor_Krieghaus",
	"visor_Reginald",
	"visor_Scar",
	"visor_WinstonStache",
	"visor_SkiGogglesWhite",
	"visor_Lava",
	"visor_polus_ice",
	"visor_SkiGoggleBlack",
	"visor_SKiGogglesOrange",
	"visor_shopglasses",
	"visor_D2CGoggles",
	"visor_is_beard",
	"visor_JanitorStache",
	"visor_Mouth",
	"visor_mira_card_blue",
	"visor_mira_card_red",
	"visor_mira_glasses",
	"visor_pk01_HazmatVisor",
	"visor_mira_mask_black",
	"visor_mira_mask_blue",
	"visor_mira_mask_green",
	"visor_mira_mask_purple",
	"visor_mira_mask_red",
	"visor_mira_mask_white",
	"visor_pk01_DumStickerVisor",
	"visor_Stickynote_Cyan",
	"visor_Stickynote_Green",
	"visor_Stickynote_Orange",
	"visor_Stickynote_Pink",
	"visor_Stickynote_Purple",
	"visor_Blush",
	"visor_Bomba",
	"visor_Carrot",
	"visor_Crack",
	"visor_Dirty",
	"visor_Dotdot",
	"visor_EyepatchL",
	"visor_EyepatchR",
	"visor_LolliBlue",
	"visor_LolliBrown",
	"visor_LolliOrange",
	"visor_LolliRed",
	"visor_PiercingL",
	"visor_PiercingR",
	"visor_SciGoggles",
	"visor_SmallGlassesBlue",
	"visor_SmallGlasses",
	"visor_SmallGlassesRed",
	"visor_Straw",
	"visor_eyeball",
	"visor_clownnose",
	"visor_masque_blue",
	"visor_masque_green",
	"visor_masque_red",
	"visor_masque_white",
	"visor_mummy",
	"visor_heim",
	"visor_jinx",
)

nameplates_dict = { # by Enby Cosmog
	'nameplate_NoPlate': 'None', 
	'nameplate_airship_Toppat': 'Airship Toppat', 
	'nameplate_airship_CCC': 'C4 Plate', 
	'nameplate_airship_Diamond': 'Diamonds!', 
	'nameplate_airship_Emerald': 'Emeralds!', 
	'nameplate_airship_Ruby': 'Rubies!', 
	'nameplate_airship_Gems': 'The Vault Above', 
	'nameplate_airship_government': 'The Greatest Nameplate', 
	'nameplate_Airship_Hull': 'Airship Hull', 
	'nameplate_airship_Sky': 'Above The Clouds', 
	'nameplate_Polus-Skyline': 'Polus Horizon', 
	'nameplate_Polus-Snowmates': 'Snowmates of Polus', 
	'nameplate_Polus_Colors': 'Colors of Polus', 
	'nameplate_Polus_DVD': 'Simsong Stan', 
	'nameplate_Polus_Ground': 'Ground Polus', 
	'nameplate_Polus_Lava': 'Lavaly', 
	'nameplate_Polus_Planet': 'Polus Planet', 
	'nameplate_Polus_Snow': 'Snowy Lands', 
	'nameplate_Polus_SpecimenBlue': 'Specimen - Blue', 
	'nameplate_Polus_SpecimenGreen': 'Specimen - Green', 
	'nameplate_Polus_SpecimenPurple': 'Specimen - Purple', 
	'nameplate_is_yard': 'Backyard', 
	'nameplate_is_dig': 'Dig2China', 
	'nameplate_is_game': 'Sports', 
	'nameplate_is_ghost': 'Ghosts', 
	'nameplate_is_green': 'Greenery', 
	'nameplate_is_sand': 'Sandstone', 
	'nameplate_is_trees': 'Trees', 
	'nameplate_Mira_Cafeteria': "Today's Menu: Pizza Juice", 
	'nameplate_Mira_Glass': 'The Sky Below', 
	'nameplate_Mira_Tiles': 'Hive Got to do Weapons', 
	'nameplate_Mira_Vines': 'Whose Vine is it Anyway?', 
	'nameplate_Mira_Wood': 'Wood You Look at That', 
	'nameplate_hw_candy': 'Candy Time', 
	'nameplate_hw_woods': 'Spooky Woods', 
	'nameplate_hw_pumpkin': 'Jack-o-Pumpkin'
}

pets_dict = { # by Enby Cosmog. special thanks to Sharedlines for the initial version of this list
	'pet_EmptyPet': 'None', 
	'pet_Alien': 'Headslug', 
	'pet_Crewmate': 'Mini Crewmate', 
	'pet_Doggy': 'Doggy', 
	'pet_Stickmin': 'H. Stickmin', 
	'pet_Hamster': 'Hampton', 
	'pet_Robot': 'Ro-bot', 
	'pet_UFO': 'UFO', 
	'pet_Ellie': 'E. Rose', 
	'pet_Squig': 'Squig', 
	'pet_Bedcrab': 'Bedcrab', 
	'pet_test': 'Glitch', 
	'pet_Lava': 'Magmate', 
	'pet_Snow': 'Snowball', 
	'pet_Charles': 'Charles Chopper', 
	'pet_Charles_Red': 'Toppat Chopper', 
	'pet_Cube': 'Deitied Cube', 
	'pet_Bush': 'Bushfriend', 
	'pet_frankendog': 'Frankendog', 
	'pet_poro': "Heimerdinger's Poro"
}
color_indexes = (  # by SharedLines
	"Red",
	"Blue",
	"Green",
	"Pink",
	"Orange",
	"Yellow",
	"Black",
	"White",
	"Purple",
	"Brown",
	"Cyan",
	"Lime",
	"Maroon",
	"Rose",
	"Banana",
	"Gray",
	"Tan",
	"Coral",
)
